language: c++
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
before_script:
  - git clone https://github.com/LoicMarechal/libMeshb
  - mkdir libMeshb/build
  - cd libMeshb/build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/tmp/install
  - make
  - cd -
script:
  - mkdir build
  - cd build
  - cmake .. -DCommons=/home/travis/build/prj-/Advection/libMeshb/build/sources/libMeshb.7.a -DCMAKE_C_FLAGS=-I/home/travis/build/prj-/Advection/libMeshb/sources
  - make
  - make install
  - cd -
notifications:
  email: false
